### GET list of players
GET http://localhost:8080/players

### GET player by id 1
GET http://localhost:8080/players/1

### GET player by id 2
GET http://localhost:8080/players/2

### GET player by id 4
GET http://localhost:8080/players/4

### CREATE new player
POST http://localhost:8080/players
Content-Type: application/json

{
  "name": "Plinicha",
  "age": 25
}

### CREATE new player with empty name
POST http://localhost:8080/players
Content-Type: application/json

{
  "name": "",
  "age": 7
}

### CREATE new player with wrong age
POST http://localhost:8080/players
Content-Type: application/json

{
  "name": "Bébécha",
  "age": 7
}

### DELETE player by id 352
DELETE http://localhost:8080/players/352

### DELETE player by id 1
DELETE http://localhost:8080/players/1

### DELETE player by id OOB
DELETE http://localhost:8080/players/9

### PUT player to edit by id 55
PUT http://localhost:8080/players/55
Content-Type: application/json

{
  "id": 55,
  "name": "Zézé l'Aventurier",
  "age": 19
}