### GET list of players
GET http://localhost:8080/players

### GET player by id 1
GET http://localhost:8080/players/1

### GET player by id 2
GET http://localhost:8080/players/2

### GET player by id 4
GET http://localhost:8080/players/4

### CREATE new player
POST http://localhost:8080/players
Content-Type: application/json

{
  "name": "Plini"
}

### DELETE player by id 3
DELETE http://localhost:8080/players/3

### DELETE player by id 1
DELETE http://localhost:8080/players/1

### DELETE player by id OOB
DELETE http://localhost:8080/players/9

### PUT player to edit by id 55
PUT http://localhost:8080/players/55
Content-Type: application/json

{
  "id": 55,
  "name": "Zézé l'Aventurier"
}