### GET request to get games catalog
GET http://localhost:8080/catalog


###
POST http://localhost:8080/games
Content-Type: application/json

{
  "type": "tictactoe",
  "playerCount": 2,
  "boardSize": 3
}

###
POST http://localhost:8080/games
Content-Type: application/json

{
  "type": "taquin",
  "playerCount": 1,
  "boardSize": 4
}

###
POST http://localhost:8080/games
Content-Type: application/json

{
  "type": "connect4",
  "playerCount": 2,
  "boardSize": 7
}

###
GET http://localhost:8080/games/bee36d96-b30f-4fd8-8887-3553b927dc3d